name: pytorch-transformer
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8.3
  - pip==20.0.2
  - matplotlib==3.1.3
  - pytorch==1.5.0
  - pip:
    - numpy==1.18.4
    - jupyter==1.0.0

