name: pytorch-transformer
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8.3
  - pip==20.0.2
  - matplotlib==3.1.3
  - pytorch==1.5.0
  - torchtext==0.6.0
  - pip:
    - GitPython==3.1.2
    - jupyter==1.0.0
    - numpy==1.18.4
    - spacy==2.3.2
    - tensorboard==2.2.2